inherit_gem: { rubocop-rails-omakase: rubocop.yml }

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

Layout/LineLength:
  Max: 80

Style/StringLiterals:
  EnforcedStyle: single_quotes
  Include:
    - "**/*.rb"
    - "**/*.rake"
    - "Gemfile"
    - "Rakefile"
